### ISSUE TITLE
How to overcome the page limit?

### ISSUE THREAD

**Issue by juniorcines** [fredsta98/keys-generator-fix#1]
Hello, this apparently cannot generate more private keys since the limit is the privatekey: fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036415f

is there any solution?

**Comment by fredsta98** [comment]
Hi, yes there is a limit to the number of private keys possible with the elliptical curve cryptography, 2^256 (2**256) to be exact, the limitations in the code are the page limitations not private key limitations. If you divide 2**256 by 128 which the number of keys per page, you get the total amount of pages each containing 128 private keys. I hope I understand your question, and this answers it.

**Comment by juniorcines** [comment]
> 

so it's not possible? The only way left is to generate private key randomly?

because I wanted to see if it was possible to continue traversing the private key after: ffffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036415f

**Comment by juniorcines** [comment]
> Hi, yes there is a limit to the number of private keys possible with the elliptical curve cryptography, 2^256 (2**256) to be exact, the limitations in the code are the page limitations not private key limitations. If you divide 2**256 by 128 which the number of keys per page, you get the total amount of pages each containing 128 private keys. I hope I understand your question, and this answers it.

Another query knows how I can do this with nodejs?

I don't understand much of "Go"

I mean, just like it generates the private key for each page, but do it with Nodejs.

Example Private Key:

0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001

Etc..

**Comment by fredsta98** [comment]
Alright well that's a whole other development all together, however, here is what you could do in theory. Build the repo for linux, I'm assuming you'll be running on a VPS, shared hosting won't give you access to `sudo`. You can then run the file and append the output to a list or dictionary, you can then display this list in the front end. I don't have a specific solution in node, but I can give you a python and perhaps PHP example of how to do so. 

```python

import os
import subprocess

def generate_page():
    """
    It generates a string of random integers (which will be used as page numbers). With a range that can be set from 1
    :return: A string of 64 random integers.
    """
    x = secrets.SystemRandom()
    x2 = x.randrange(1,1157920892373162048957175037071891804814762242860091859379119497041412096)
    return str(x2)

# Generate a random page number, alternatively you can use 'page = input()'.
page = generate_page()

# Get the output from terminal
btc_output = subprocess.getoutput(f"./keys-generator btc {page}")

eth_output = subprocess.getoutput(f"./keys-generator eth {page}")

# Print the private keys and addresses
print(btc_output)

print(eth_output)

# You could also use the search feature similarly.

# Get the private keys from user

btc_private_key = input()

eth_private_key = input()

# Search
btc_search = subprocess.getoutput(f"./keys-generator btc-search {btc_private_key}")

eth_search = subprocess.getoutput(f"./keys-generator eth-search {eth_private_key}")

# Print results
print(btc_search)

print(eth_search)
```

You can use this to get the results of the terminal and display them in a frontend, I'd do it in Django.

Instruction are clear on how to build, but if you have any issues you can find the binaries here: https://github.com/fredsta98/keys-generator-binaries

An example for how to do what I think you might be trying to do is: https://github.com/fredsta98/keys a PHP implementation that uses the linux binary and PHP the same way keys.lol does. Hope this helps, feel free to ask any other question.

**Comment by juniorcines** [comment]
> Alright well that's a whole other development all together, however, here is what you could do in theory. Build the repo for linux, I'm assuming you'll be running on a VPS, shared hosting won't give you access to . You can then run the file and append the output to a list or dictionary, you can then display this list in the front end. I don't have a specific solution in node, but I can give you a python and perhaps PHP example of how to do so.`sudo`
> 
> ```python
> import os
> import subprocess
> 
> def generate_page():
>     """
>     It generates a string of random integers (which will be used as page numbers). With a range that can be set from 1
>     :return: A string of 64 random integers.
>     """
>     x = secrets.SystemRandom()
>     x2 = x.randrange(1,1157920892373162048957175037071891804814762242860091859379119497041412096)
>     return str(x2)
> 
> # Generate a random page number, alternatively you can use 'page = input()'.
> page = generate_page()
> 
> # Get the output from terminal
> btc_output = subprocess.getoutput(f"./keys-generator btc {page}")
> 
> eth_output = subprocess.getoutput(f"./keys-generator eth {page}")
> 
> # Print the private keys and addresses
> print(btc_output)
> 
> print(eth_output)
> 
> # You could also use the search feature similarly.
> 
> # Get the private keys from user
> 
> btc_private_key = input()
> 
> eth_private_key = input()
> 
> # Search
> btc_search = subprocess.getoutput(f"./keys-generator btc-search {btc_private_key}")
> 
> eth_search = subprocess.getoutput(f"./keys-generator eth-search {eth_private_key}")
> 
> # Print results
> print(btc_search)
> 
> print(eth_search)
> ```
> 
> You can use this to get the results of the terminal and display them in a frontend, I'd do it in Django.

I don't know anything about python or django.

I don't know if you could help me with the code already being in nodejs?

I would really appreciate it.

**Comment by fredsta98** [comment]
I updated the comment... there's a web implementation for how to do this: https://github.com/fredsta98/keys however if you need further help, email: leehaung141@gmail.com, I'm mark this issue as closed now.
